name: riverpod_countup
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations: #追加

    sdk: flutter         #追加
  cupertino_icons: ^1.0.2
  intl: ^0.17.0          #追加
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0

dev_dependencies:

  flutter_test:

    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  freezed: ^2.0.2
  json_serializable: ^6.2.0
  test: ^1.21.4

flutter:
  uses-material-design: true

  generate: true         #追加
